language: node_js

node_js:
  - node
  - lts/*
  - 8

services:
  - postgresql

branches:
  only:
    - develop

script:
  - npm run coverage

env: >
  NODE_ENV=test
  TEST_APP_PORT='4401'
  TEST_DATABASE_URL='postgres://postgres@localhost:5432/wayfarer_test'
  TEST_DB='wayfarer_test'

before_script:
  - cp .env.example .env
  - psql -c 'create database wayfarer_test;' -U postgres

after_success: npm run dbdroptables
