language: node_js

node_js:
  - node
  - lts/*
  - 8

services:
  - postgresql

branches:
  only:
    - develop

script:
  - npm run coverage

env: >
  NODE_ENV=test
  TEST_APP_PORT='4401'
  TEST_DATABASE_URL='postgres://postgres:admin@localhost:5432/wayfarer_test'

# after_success: npm run coverage
